# Generated by Django 3.1.2 on 2020-10-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cus_signup_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_password', models.CharField(max_length=200)),
            ],
        ),
    ]
