# Generated by Django 3.1.2 on 2020-10-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokanapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cus_signup_table',
            new_name='Customer_information',
        ),
    ]
